language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer update
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email: "royopa@gmail.com"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
