language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
     - php: hhvm

env:
  - SYMFONY_VERSION='2.5.*' ROYOPAPDFBUNDLE_VERSION='dev-master as 1.0'

before_script:
  - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
  - composer require --no-update royopa/pdf-bundle=${ROYOPAPDFBUNDLE_VERSION}
  - composer install --prefer-source
