language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION='2.5.*'

before_script:
  - composer require --no-interaction --no-update symfony/symfony=${SYMFONY_VERSION}
  - composer require --no-interaction --no-update royopa/pdf-bundle=dev-master
  - composer install --prefer-source

matrix:
  allow_failures:
     - php: hhvm
